FROM python:2.7
LABEL maintainer="Tina Wu"

COPY ./techtrends /app
WORKDIR /app
RUN pip install -r requirements.txt

EXPOSE 3111

RUN ["/bin/bash", "-c", "python init_db.py"]

# command to run on container start
CMD [ "python", "app.py" ]
